version: "3"
services:
  front:
    build: .
    tty: true
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/app
      - front_node_modules:/app/node_modules
    working_dir: /app
    command: yarn dev
volumes:
  front_node_modules:

